export const makes = [
  "Audi",
  "BMW",
  "Citroen",
  "Dacia",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Jaguar",
  "Kia",
  "Land Rover",
  "Mazda",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Renault",
  "Seat",
  "Skoda",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Vauxhall",
  "Volkswagen",
  "Volvo",
];

export const counties = [
  "Carlow",
  "Cavan",
  "Clare",
  "Cork",
  "Donegal",
  "Dublin",
  "Galway",
  "Kerry",
  "Kildare",
  "Kilkenny",
  "Laois",
  "Leitrim",
  "Limerick",
  "Longford",
  "Louth",
  "Mayo",
  "Meath",
  "Monaghan",
  "Offaly",
  "Roscommon",
  "Sligo",
  "Tipperary",
  "Waterford",
  "Westmeath",
  "Wexford",
  "Wicklow",
  "Antrim",
  "Armagh",
  "Derry",
  "Down",
  "Fermanagh",
  "Tyrone",
];

export const bodyTypes = [
  "Hatchback",
  "Saloon",
  "Estate",
  "SUV",
  "Coupe",
  "Convertible",
  "MPV",
  "Van",
];

export const fuelTypes = ["Petrol", "Diesel", "Hybrid", "Electric"];

export const yearRange = Array.from(
  { length: 2026 - 2005 + 1 },
  (_, i) => 2026 - i
);

export const priceRanges = [
  { label: "Up to €5,000", min: 0, max: 5000 },
  { label: "€5,000 - €10,000", min: 5000, max: 10000 },
  { label: "€10,000 - €15,000", min: 10000, max: 15000 },
  { label: "€15,000 - €20,000", min: 15000, max: 20000 },
  { label: "€20,000 - €25,000", min: 20000, max: 25000 },
  { label: "€25,000 - €30,000", min: 25000, max: 30000 },
  { label: "€30,000 - €40,000", min: 30000, max: 40000 },
  { label: "€40,000+", min: 40000, max: Infinity },
];

export const colours = [
  "Black",
  "White",
  "Silver",
  "Grey",
  "Blue",
  "Red",
  "Green",
  "Brown",
  "Beige",
  "Orange",
  "Yellow",
  "Gold",
  "Purple",
  "Other",
];
