import { Car } from "./types";

export const cars: Car[] = [
  {
    id: "1",
    title: "2021 Volkswagen Golf 1.5 TSI Style",
    make: "Volkswagen",
    model: "Golf",
    year: 2021,
    price: 24950,
    mileage: 42000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineSize: "1.5L",
    bodyType: "Hatchback",
    colour: "Atlantic Blue",
    doors: 5,
    county: "Cork",
    nctExpiry: "03/2026",
    taxExpiry: "06/2026",
    description:
      "Immaculate Volkswagen Golf in stunning Atlantic Blue. Full VW service history, one owner from new. Loaded with features including adaptive cruise control, parking sensors, and the latest infotainment system. Must be seen to be appreciated.",
    features: [
      "Adaptive Cruise Control",
      "Apple CarPlay",
      "Android Auto",
      "Heated Seats",
      "Parking Sensors",
      "LED Headlights",
      "Alloy Wheels",
      "Bluetooth",
    ],
    images: ["/cars/vw-golf-1.jpg", "/cars/vw-golf-2.jpg"],
    sellerType: "owner",
    featured: true,
    dateAdded: "2025-04-10",
    previousOwners: 1,
  },
  {
    id: "2",
    title: "2020 Toyota Corolla 1.8 Hybrid Luna",
    make: "Toyota",
    model: "Corolla",
    year: 2020,
    price: 22500,
    mileage: 55000,
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineSize: "1.8L",
    bodyType: "Saloon",
    colour: "Glacier White",
    doors: 4,
    county: "Dublin",
    nctExpiry: "09/2025",
    taxExpiry: "12/2025",
    description:
      "Exceptional Toyota Corolla Hybrid with incredibly low running costs. A1 road tax band. Full Toyota dealer service history. Drives like new with smooth hybrid powertrain. Perfect commuter car.",
    features: [
      "Hybrid System",
      "Reversing Camera",
      "Touchscreen Display",
      "Lane Departure Warning",
      "Automatic Headlights",
      "Climate Control",
      "Alloy Wheels",
      "Cruise Control",
    ],
    images: ["/cars/corolla-1.jpg", "/cars/corolla-2.jpg"],
    sellerType: "commission",
    featured: true,
    dateAdded: "2025-04-08",
    previousOwners: 1,
  },
  {
    id: "3",
    title: "2019 BMW 320d M Sport",
    make: "BMW",
    model: "3 Series",
    year: 2019,
    price: 29950,
    mileage: 68000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "2.0L",
    bodyType: "Saloon",
    colour: "Mineral Grey",
    doors: 4,
    county: "Limerick",
    nctExpiry: "05/2025",
    taxExpiry: "03/2026",
    description:
      "Stunning BMW 320d M Sport with the desirable 2.0 diesel engine. Excellent fuel economy for a premium saloon. Full leather M Sport interior, heads-up display, and professional navigation. This car has it all.",
    features: [
      "M Sport Package",
      "Leather Interior",
      "Heads-Up Display",
      "Professional Navigation",
      "Harman Kardon Sound",
      "Parking Assist",
      "Sport Seats",
      "19\" M Sport Alloys",
    ],
    images: ["/cars/bmw-320d-1.jpg", "/cars/bmw-320d-2.jpg"],
    sellerType: "commission",
    featured: true,
    dateAdded: "2025-04-05",
    previousOwners: 2,
  },
  {
    id: "4",
    title: "2022 Hyundai Tucson 1.6 CRDi Executive",
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    price: 32000,
    mileage: 28000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "1.6L",
    bodyType: "SUV",
    colour: "Shadow Grey",
    doors: 5,
    county: "Galway",
    nctExpiry: "01/2027",
    taxExpiry: "08/2026",
    description:
      "Brand new shape Hyundai Tucson in the top-spec Executive trim. This SUV is loaded with every conceivable option. Striking design inside and out. 5 year Hyundai warranty still remaining. Excellent value.",
    features: [
      "Panoramic Sunroof",
      "Blind Spot Monitoring",
      "Heated & Ventilated Seats",
      "360° Camera",
      "Wireless Charging",
      "Premium Sound System",
      "Smart Electric Tailgate",
      "Full LED Lights",
    ],
    images: ["/cars/tucson-1.jpg", "/cars/tucson-2.jpg"],
    sellerType: "owner",
    featured: true,
    dateAdded: "2025-04-12",
    previousOwners: 1,
  },
  {
    id: "5",
    title: "2018 Ford Focus 1.5 TDCi Titanium",
    make: "Ford",
    model: "Focus",
    year: 2018,
    price: 14500,
    mileage: 89000,
    fuelType: "Diesel",
    transmission: "Manual",
    engineSize: "1.5L",
    bodyType: "Hatchback",
    colour: "Magnetic Grey",
    doors: 5,
    county: "Waterford",
    nctExpiry: "11/2025",
    taxExpiry: "04/2026",
    description:
      "Well-maintained Ford Focus Titanium with excellent specification. Great on fuel with the efficient 1.5 TDCi engine. Full service history, new tyres just fitted. A reliable and practical family car.",
    features: [
      "SYNC 3 Infotainment",
      "Rear Parking Sensors",
      "Heated Windscreen",
      "Cruise Control",
      "Dual Zone Climate Control",
      "Auto Wipers",
      "Auto Headlights",
      "DAB Radio",
    ],
    images: ["/cars/focus-1.jpg", "/cars/focus-2.jpg"],
    sellerType: "commission",
    featured: false,
    dateAdded: "2025-04-01",
    previousOwners: 2,
  },
  {
    id: "6",
    title: "2023 Skoda Octavia 2.0 TDI Style",
    make: "Skoda",
    model: "Octavia",
    year: 2023,
    price: 28500,
    mileage: 18000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "2.0L",
    bodyType: "Estate",
    colour: "Lava Blue",
    doors: 5,
    county: "Kerry",
    nctExpiry: "07/2027",
    taxExpiry: "10/2026",
    description:
      "Nearly new Skoda Octavia Estate in the popular Style trim. The estate version offers an enormous boot making it perfect for families. Smooth DSG automatic gearbox. Balance of manufacturer warranty remaining.",
    features: [
      "Virtual Cockpit",
      "Columbus Navigation",
      "Adaptive Cruise Control",
      "Front Assist",
      "Lane Assist",
      "Wireless Apple CarPlay",
      "Heated Seats",
      "Electric Tailgate",
    ],
    images: ["/cars/octavia-1.jpg", "/cars/octavia-2.jpg"],
    sellerType: "owner",
    featured: false,
    dateAdded: "2025-03-28",
    previousOwners: 1,
  },
  {
    id: "7",
    title: "2020 Audi A4 2.0 TDI S Line",
    make: "Audi",
    model: "A4",
    year: 2020,
    price: 27500,
    mileage: 62000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "2.0L",
    bodyType: "Saloon",
    colour: "Navarra Blue",
    doors: 4,
    county: "Tipperary",
    nctExpiry: "02/2026",
    taxExpiry: "07/2026",
    description:
      "Beautiful Audi A4 S Line in the rare Navarra Blue metallic. Excellent condition throughout with full Audi service history. S Line exterior and interior package gives this car real road presence.",
    features: [
      "S Line Exterior",
      "S Line Interior",
      "MMI Navigation Plus",
      "Virtual Cockpit",
      "Bang & Olufsen Sound",
      "Matrix LED Headlights",
      "Sport Suspension",
      "Privacy Glass",
    ],
    images: ["/cars/audi-a4-1.jpg", "/cars/audi-a4-2.jpg"],
    sellerType: "commission",
    featured: false,
    dateAdded: "2025-03-25",
    previousOwners: 1,
  },
  {
    id: "8",
    title: "2017 Nissan Qashqai 1.5 dCi SVE",
    make: "Nissan",
    model: "Qashqai",
    year: 2017,
    price: 15950,
    mileage: 95000,
    fuelType: "Diesel",
    transmission: "Manual",
    engineSize: "1.5L",
    bodyType: "SUV",
    colour: "Pearl Black",
    doors: 5,
    county: "Wexford",
    nctExpiry: "08/2025",
    taxExpiry: "01/2026",
    description:
      "Top spec Nissan Qashqai SVE with panoramic roof and leather seats. This is Ireland's best-selling crossover for good reason — practical, reliable, and great to drive. Full Nissan service history.",
    features: [
      "Panoramic Glass Roof",
      "Leather Seats",
      "360° Around View Monitor",
      "NissanConnect Navigation",
      "Intelligent Key",
      "Dual Zone Climate Control",
      "19\" Alloy Wheels",
      "Roof Rails",
    ],
    images: ["/cars/qashqai-1.jpg", "/cars/qashqai-2.jpg"],
    sellerType: "owner",
    featured: false,
    dateAdded: "2025-03-20",
    previousOwners: 2,
  },
  {
    id: "9",
    title: "2021 Peugeot 3008 1.5 BlueHDi Allure",
    make: "Peugeot",
    model: "3008",
    year: 2021,
    price: 26750,
    mileage: 45000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "1.5L",
    bodyType: "SUV",
    colour: "Pearl White",
    doors: 5,
    county: "Cork",
    nctExpiry: "04/2026",
    taxExpiry: "09/2026",
    description:
      "Stylish Peugeot 3008 Allure with the award-winning i-Cockpit interior. This SUV stands out with its bold design and premium cabin feel. Excellent fuel economy from the BlueHDi engine. A great all-rounder.",
    features: [
      "i-Cockpit Digital Display",
      "Grip Control",
      "Rear Camera",
      "Active Safety Brake",
      "Connected Navigation",
      "Wireless Phone Charging",
      "Full LED Headlights",
      "18\" Alloys",
    ],
    images: ["/cars/3008-1.jpg", "/cars/3008-2.jpg"],
    sellerType: "commission",
    featured: false,
    dateAdded: "2025-03-15",
    previousOwners: 1,
  },
  {
    id: "10",
    title: "2022 Tesla Model 3 Standard Range Plus",
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 33950,
    mileage: 22000,
    fuelType: "Electric",
    transmission: "Automatic",
    engineSize: "Electric",
    bodyType: "Saloon",
    colour: "Midnight Silver",
    doors: 4,
    county: "Dublin",
    nctExpiry: "10/2026",
    taxExpiry: "N/A - Electric",
    description:
      "Tesla Model 3 in excellent condition with low mileage. Zero road tax, zero fuel costs when charging at home. Autopilot included. Over-the-air updates keep adding new features. The future of motoring.",
    features: [
      "Autopilot",
      "15\" Touchscreen",
      "Glass Roof",
      "Premium Connectivity",
      "Wireless Phone Charging",
      "Sentry Mode",
      "Supercharger Access",
      "Premium Sound System",
    ],
    images: ["/cars/tesla-1.jpg", "/cars/tesla-2.jpg"],
    sellerType: "owner",
    featured: true,
    dateAdded: "2025-04-14",
    previousOwners: 1,
  },
  {
    id: "11",
    title: "2019 Mercedes-Benz A180 AMG Line",
    make: "Mercedes-Benz",
    model: "A-Class",
    year: 2019,
    price: 23950,
    mileage: 52000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "1.3L",
    bodyType: "Hatchback",
    colour: "Cosmos Black",
    doors: 5,
    county: "Meath",
    nctExpiry: "06/2025",
    taxExpiry: "11/2025",
    description:
      "Mercedes-Benz A-Class with the sporty AMG Line package. Features the stunning MBUX infotainment system with 'Hey Mercedes' voice control. Full Mercedes service history. A premium hatchback that turns heads.",
    features: [
      "AMG Line Exterior",
      "MBUX Infotainment",
      "Widescreen Cockpit",
      "Ambient Lighting",
      "Reversing Camera",
      "Active Parking Assist",
      "Keyless Go",
      "18\" AMG Alloys",
    ],
    images: ["/cars/a-class-1.jpg", "/cars/a-class-2.jpg"],
    sellerType: "commission",
    featured: false,
    dateAdded: "2025-03-10",
    previousOwners: 1,
  },
  {
    id: "12",
    title: "2020 Kia Sportage 1.6 CRDi K3",
    make: "Kia",
    model: "Sportage",
    year: 2020,
    price: 21500,
    mileage: 58000,
    fuelType: "Diesel",
    transmission: "Manual",
    engineSize: "1.6L",
    bodyType: "SUV",
    colour: "Inferno Red",
    doors: 5,
    county: "Clare",
    nctExpiry: "12/2025",
    taxExpiry: "05/2026",
    description:
      "Popular Kia Sportage in eye-catching Inferno Red. Well-equipped K3 spec with all the features you need. Remaining Kia 7-year warranty gives total peace of mind. A practical family SUV at a great price.",
    features: [
      "8\" Touchscreen",
      "Apple CarPlay & Android Auto",
      "Rear Parking Camera",
      "Heated Front Seats",
      "Privacy Glass",
      "Roof Rails",
      "17\" Alloys",
      "Auto Air Conditioning",
    ],
    images: ["/cars/sportage-1.jpg", "/cars/sportage-2.jpg"],
    sellerType: "owner",
    featured: false,
    dateAdded: "2025-03-05",
    previousOwners: 1,
  },
];

export const makes = [
  "Audi",
  "BMW",
  "Ford",
  "Hyundai",
  "Kia",
  "Mercedes-Benz",
  "Nissan",
  "Peugeot",
  "Skoda",
  "Tesla",
  "Toyota",
  "Volkswagen",
];

export const counties = [
  "Carlow",
  "Cavan",
  "Clare",
  "Cork",
  "Donegal",
  "Dublin",
  "Galway",
  "Kerry",
  "Kildare",
  "Kilkenny",
  "Laois",
  "Leitrim",
  "Limerick",
  "Longford",
  "Louth",
  "Mayo",
  "Meath",
  "Monaghan",
  "Offaly",
  "Roscommon",
  "Sligo",
  "Tipperary",
  "Waterford",
  "Westmeath",
  "Wexford",
  "Wicklow",
];

export const bodyTypes = [
  "Hatchback",
  "Saloon",
  "Estate",
  "SUV",
  "Coupe",
  "Convertible",
  "MPV",
  "Van",
];

export const fuelTypes = ["Petrol", "Diesel", "Hybrid", "Electric"];

export const yearRange = Array.from(
  { length: 2025 - 2010 + 1 },
  (_, i) => 2025 - i
);

export const priceRanges = [
  { label: "Up to €5,000", min: 0, max: 5000 },
  { label: "€5,000 - €10,000", min: 5000, max: 10000 },
  { label: "€10,000 - €15,000", min: 10000, max: 15000 },
  { label: "€15,000 - €20,000", min: 15000, max: 20000 },
  { label: "€20,000 - €25,000", min: 20000, max: 25000 },
  { label: "€25,000 - €30,000", min: 25000, max: 30000 },
  { label: "€30,000 - €40,000", min: 30000, max: 40000 },
  { label: "€40,000+", min: 40000, max: Infinity },
];
