[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://lxvwefcnnkjikoncaxcl.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_GMHoKqx2SEWZEl0cHaCzRg_Xd_XfbE0"
